version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5433:5432
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
